version: '3'
services:
  camunda_bpm_0:
    build: 
      context: .
      dockerfile: Dockerfile # change to Dockerfile.session or Dockerfile.kryo
    expose: 
      - "8080"
    depends_on:
      - redis
  camunda_bpm_1:
    build:
      context: .
      dockerfile: Dockerfile # change to Dockerfile.session or Dockerfile.kryo
    expose: 
      - "8080"
    depends_on:
      - redis
  redis:
    image: redis:3.2-alpine
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - camunda_bpm_0
      - camunda_bpm_1
    ports:
      - "80:80"
